s="Hello World"

print( s.capitalize() )
print( s.casefold() )
print( s.center(20,'^') )
print( s.count('o') )
print( s.encode() )
print( s.endswith('ld') )
print( s.expandtabs(1) )
print( s.find("le") )
print( s.format() )
print( s.index('ld') )
print( s.isalnum() )
print( s.isalpha() )
print( s.isascii() )
print( s.isdecimal() )
print( s.isdigit() )
print( "s".isidentifier() )
print( s.islower() )
print( s.isnumeric() )
print( s.isprintable() )
print( s.isspace() )
print( s.istitle() )
print( s.isupper() )
print( s.join([' a ',' b ',' c ',' d ']) )
print( s.ljust(20,'*') )
print( s.lower() )
print( s.lstrip() )
print( s.partition(" ") )
print( s.replace("World","Python") )
print( s.rfind('0') )
print( s.rindex("o") )
print( s.rjust(20,'*') )
print( s.rpartition(' ') )
print( s.rstrip() )
print( s.split() )
print( s.splitlines() )
print( s.startswith("He") )
print( s.strip() )
print( s.swapcase() )
print( s.title() )
print( s.upper() )
print( s.zfill(20) )
